builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
archives:
  - id: default
    replacements:
      darwin: Darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - name: pomdok
    tap:
      owner: jolicode
      name: pomdok
      branch: master
    folder: Formula
    homepage: "https://github.com/jolicode/pomdok"
    description: "Simple wrapper to Symfony Go Binary for multi-app."
    dependencies:
      - wget
      - nss
