# This file was generated by GoReleaser. DO NOT EDIT.
class Pomdok < Formula
  desc "Simple wrapper to Symfony Go Binary for multi-app."
  homepage "https://github.com/Korbeil/pomdok"
  url "https://github.com/Korbeil/pomdok/releases/download/1.0.0/pomdok_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "83c41b6c729b222c2e861b607c637fc3dbddb277d308bdbb5429d9542541e0d1"
  
  depends_on "wget"
  depends_on "nss"

  def install
    bin.install "pomdok"
  end
end
